(()=>{'use strict';
 const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const date=v=>new Date(v).toLocaleString();let selected=null,entries=[];
 async function api(path,body){const r=await fetch('/api/training'+path,{method:body===undefined?'GET':'POST',headers:{authorization:`Bearer ${sessionStorage.getItem('nexusAccessToken')||''}`,'content-type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),cache:'no-store'});if(!r.ok){const e=await r.json();throw Error(e.error||'Request failed')}return r.headers.get('content-type')?.includes('application/pdf')?r.blob():r.json()}
 const panel=document.createElement('section');panel.className='panel report';panel.id='reviewQueue';panel.innerHTML='<h3>Approval notifications</h3><p>Approve submissions before their assignment due date. Email reminders start three days before the deadline and continue daily while approval is overdue.</p><div id="approvalQueue" class="cards"></div><h3>Central document library</h3><p>Policy versions and supporting documents are retained here. Signed acknowledgments and approval history appear in Training records below. External courses open at their provider.</p><label>Search documents<input id="documentSearch" type="search" placeholder="Staff, document or version"></label><div id="centralDocuments" class="cards"></div>';$('#administration').prepend(panel);
 const evidence=document.createElement('section');evidence.innerHTML='<h3>Supporting documents</h3><div id="evidenceFiles"></div><form id="evidenceUpload"><label>Certificate or supporting PDF (up to 4 MB)<input name="file" type="file" accept="application/pdf" required></label><button type="submit">Upload document</button><p role="status"></p></form>';$('#ackForm').before(evidence);
 function renderLibrary(){const term=$('#documentSearch').value.toLowerCase();$('#centralDocuments').innerHTML=entries.filter(e=>e.text.toLowerCase().includes(term)).map(e=>`<article class="assignment"><p>${esc(e.text)}</p><button data-document-path="${esc(e.path)}">Open document</button></article>`).join('')||'<p>No documents match.</p>'}
 window.loadTrainingReview=async(materials,records)=>{
  const documents=(await api('/admin/documents')).documents;
  const pending=records.filter(r=>r.status==='AWAITING_VERIFICATION').sort((a,b)=>new Date(a.due_at)-new Date(b.due_at));
  $('#approvalQueue').innerHTML=pending.length?pending.map(r=>`<article class="assignment"><span class="badge ${new Date(r.due_at)<new Date()?'OVERDUE':'AWAITING_VERIFICATION'}">${new Date(r.due_at)<new Date()?'Approval overdue':'Awaiting approval'}</span><h4>${esc(r.display_name||r.email)} · ${esc(r.title)}</h4><p>Approve by ${esc(date(r.due_at))}</p><p>Submitted ${esc(date(r.acknowledged_at))} by ${esc(r.acknowledged_name)}</p><p>${esc(r.acknowledgment_text)}</p><button data-document-path="/admin/materials/${esc(r.material_id)}/file">Review assigned material</button>${documents.filter(d=>d.assignment_id===r.id).map(d=>`<button data-document-path="/documents/${esc(d.id)}/file">${esc(d.filename)}</button>`).join('')}<button data-review-approval="${esc(r.id)}">Review approval</button></article>`).join(''):'<p>No submissions awaiting approval.</p>';
  entries=[...materials.map(m=>({text:`${m.title} · Version ${m.version}`,path:`/admin/materials/${m.id}/file`})),...documents.map(d=>({text:`${d.display_name} · ${d.title} · ${d.filename} · ${date(d.created_at)}`,path:`/documents/${d.id}/file`}))];renderLibrary();
 };
 $('#documentSearch').oninput=renderLibrary;
 panel.onclick=event=>{const b=event.target.closest('[data-review-approval]');if(b){$('#reportFilter').value='';$('#reportFilter').dispatchEvent(new Event('input'));document.querySelector(`#reportRows [data-verify="${b.dataset.reviewApproval}"]`)?.click()}};
 let documentUrl=null;const viewer=document.createElement('dialog');viewer.id='documentViewer';viewer.innerHTML='<button type="button">Close document</button><div></div>';document.body.append(viewer);viewer.querySelector('button').onclick=()=>viewer.close();viewer.onclose=()=>{if(documentUrl)URL.revokeObjectURL(documentUrl);documentUrl=null;viewer.querySelector('div').replaceChildren()};
 document.addEventListener('click',async event=>{const b=event.target.closest('[data-document-path]');if(!b)return;viewer.showModal();const content=viewer.querySelector('div');content.textContent='Loading document…';try{const data=await api(b.dataset.documentPath);if(!viewer.open)return;if(data instanceof Blob){documentUrl=URL.createObjectURL(data);content.innerHTML=`<iframe title="Review document" style="width:100%;height:65vh" src="${documentUrl}"></iframe><a href="${documentUrl}" target="_blank" rel="noopener">Open PDF</a>`}else{content.innerHTML=`<a href="${esc(data.resourceUrl)}" target="_blank" rel="noopener noreferrer">Open external material</a>`}}catch(error){content.textContent=error.message}});
 window.loadTrainingEvidence=async assignment=>{selected=assignment;$('#evidenceUpload').hidden=Boolean(assignment.acknowledged_at);$('#evidenceUpload p').textContent='';const data=await api(`/assignments/${assignment.id}/documents`);if(selected?.id!==assignment.id)return;$('#evidenceFiles').innerHTML=data.documents.map(d=>`<p><button data-document-path="/documents/${esc(d.id)}/file">${esc(d.filename)}</button></p>`).join('')||'<p>No supporting documents uploaded.</p>'};
 $('#evidenceUpload').onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button'),message=form.querySelector('p'),id=selected.id;button.disabled=true;try{const file=form.elements.file.files[0];if(!file||file.size>4*1024*1024)throw Error('Choose a PDF up to 4 MB');const dataBase64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(Error('Unable to read PDF'));reader.readAsDataURL(file)});await api(`/assignments/${id}/documents`,{filename:file.name,dataBase64});if(selected.id===id){await window.loadTrainingEvidence(selected);form.reset();message.textContent='Document stored. Submit your acknowledgment when ready.'}}catch(error){message.textContent=error.message}finally{button.disabled=false}};
})();
