BEGIN;

-- Ensure schema_migrations table exists to track applied migrations
CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  description text,
  applied_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS users (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  email text UNIQUE NOT NULL,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'USER',
  scope_id text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure all required columns exist (idempotent for pre-existing tables)
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS role text DEFAULT 'USER';
ALTER TABLE users ADD COLUMN IF NOT EXISTS scope_id text;
ALTER TABLE users ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_users_email ON users(lower(email));
CREATE INDEX IF NOT EXISTS idx_users_role ON users(role) WHERE active = true;

CREATE TABLE IF NOT EXISTS bookings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reference text UNIQUE NOT NULL,
  patient_code text,
  vehicle_id bigint,
  status text NOT NULL DEFAULT 'PENDING',
  service_type text,
  pickup_time timestamptz,
  dropoff_time timestamptz,
  pickup_location text,
  dropoff_location text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- Ensure all required bookings columns exist (idempotent for pre-existing tables)
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS reference text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS patient_code text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS vehicle_id bigint;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS status text DEFAULT 'PENDING';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS service_type text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_time timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS dropoff_time timestamptz;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_location text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS dropoff_location text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_bookings_reference ON bookings(reference);
CREATE INDEX IF NOT EXISTS idx_bookings_status_time ON bookings(status, created_at DESC);

INSERT INTO schema_migrations(version,description) VALUES('001.001','Base schema: users and bookings tables') ON CONFLICT(version) DO NOTHING;

COMMIT;
