BEGIN;
CREATE TABLE IF NOT EXISTS facilities (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 facility_code text UNIQUE NOT NULL,
 name text NOT NULL,
 account_number text UNIQUE,
 contact_name text,
 contact_email text,
 contact_phone text,
 address text,
 billing_type text,
 credit_limit numeric(12,2),
 terms text,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS patients (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 patient_code text UNIQUE NOT NULL,
 facility_code text,
 display_name text NOT NULL,
 phone text,
 email text,
 mobility text,
 payer text,
 preferred_language text,
 pickup_address text,
 notes text,
 active boolean NOT NULL DEFAULT true,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);
-- Ensure facility_code column exists and add foreign key constraint
ALTER TABLE patients ADD COLUMN IF NOT EXISTS facility_code text;
ALTER TABLE patients DROP CONSTRAINT IF EXISTS fk_patients_facility CASCADE;
ALTER TABLE patients ADD CONSTRAINT fk_patients_facility FOREIGN KEY (facility_code) REFERENCES facilities(facility_code) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_patients_facility_active ON patients(facility_code,active);
-- Ensure patient_code column exists (for recurring_trips foreign key reference)
ALTER TABLE patients ADD COLUMN IF NOT EXISTS patient_code text UNIQUE;
CREATE TABLE IF NOT EXISTS vehicles (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 unit_number text UNIQUE NOT NULL,
 vehicle_type text NOT NULL,
 status text NOT NULL DEFAULT 'AVAILABLE',
 latitude numeric(10,7), longitude numeric(10,7), heading numeric(6,2), speed_mph numeric(6,2),
 driver_scope_id text, last_seen_at timestamptz,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_vehicles_status_seen ON vehicles(status,last_seen_at DESC);
CREATE TABLE IF NOT EXISTS recurring_trips (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 recurrence_code text UNIQUE NOT NULL,
 patient_code text NOT NULL,
 service text NOT NULL, days text[] NOT NULL DEFAULT '{}', pickup_time time NOT NULL,
 return_time time, pickup text NOT NULL, destination text NOT NULL,
 start_date date NOT NULL, end_date date, status text NOT NULL DEFAULT 'ACTIVE',
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
-- Ensure patient_code foreign key constraint exists for recurring_trips
ALTER TABLE recurring_trips DROP CONSTRAINT IF EXISTS fk_recurring_trips_patient CASCADE;
ALTER TABLE recurring_trips ADD CONSTRAINT fk_recurring_trips_patient FOREIGN KEY (patient_code) REFERENCES patients(patient_code) ON DELETE CASCADE;
CREATE TABLE IF NOT EXISTS invoices (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 invoice_number text UNIQUE NOT NULL,
 booking_reference text,
 facility_code text,
 amount numeric(12,2) NOT NULL DEFAULT 0, status text NOT NULL DEFAULT 'DRAFT',
 due_date date, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);
-- Ensure invoices columns exist and add foreign key constraints
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS booking_reference text;
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS facility_code text;
ALTER TABLE invoices DROP CONSTRAINT IF EXISTS fk_invoices_booking CASCADE;
ALTER TABLE invoices DROP CONSTRAINT IF EXISTS fk_invoices_facility CASCADE;
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_booking FOREIGN KEY (booking_reference) REFERENCES bookings(reference) ON DELETE SET NULL;
ALTER TABLE invoices ADD CONSTRAINT fk_invoices_facility FOREIGN KEY (facility_code) REFERENCES facilities(facility_code) ON DELETE SET NULL;
INSERT INTO schema_migrations(version,description) VALUES('041.001','Production repository tables for facilities, patients, vehicles, recurring trips, and invoices') ON CONFLICT(version) DO NOTHING;
COMMIT;
