BEGIN;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_lat numeric(10,7);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS pickup_lng numeric(10,7);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS destination_lat numeric(10,7);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS destination_lng numeric(10,7);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS distance_miles numeric(10,2);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS estimated_duration text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS estimated_fare numeric(12,2);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_status text NOT NULL DEFAULT 'UNPAID';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS stripe_payment_intent_id text;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS notification_status jsonb NOT NULL DEFAULT '{}'::jsonb;
CREATE TABLE IF NOT EXISTS integration_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 provider text NOT NULL,event_type text NOT NULL,external_id text,idempotency_key text,
 status text NOT NULL DEFAULT 'RECEIVED',payload jsonb NOT NULL DEFAULT '{}'::jsonb,
 error_message text,created_at timestamptz NOT NULL DEFAULT now(),processed_at timestamptz
);
CREATE UNIQUE INDEX IF NOT EXISTS ux_integration_events_provider_idempotency ON integration_events(provider,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_integration_events_created ON integration_events(provider,created_at DESC);
CREATE TABLE IF NOT EXISTS gps_positions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 vehicle_unit text NOT NULL,driver_scope_id text,booking_reference text,
 latitude numeric(10,7) NOT NULL,longitude numeric(10,7) NOT NULL,
 heading numeric(6,2),speed_mph numeric(6,2),accuracy_m numeric(8,2),recorded_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_gps_positions_vehicle_time ON gps_positions(vehicle_unit,recorded_at DESC);
INSERT INTO schema_migrations(version,description) VALUES('042.001','Unified booking, real-time integrations, payments, notifications and GPS events') ON CONFLICT(version) DO NOTHING;
COMMIT;
