CREATE TABLE IF NOT EXISTS employees (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id uuid UNIQUE REFERENCES users(id) ON DELETE SET NULL,
 employee_code text UNIQUE NOT NULL,
 role text NOT NULL,
 display_name text NOT NULL,
 email text,
 phone text,
 unit_number text,
 timezone text NOT NULL DEFAULT 'America/New_York',
 active boolean NOT NULL DEFAULT true,
 metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE employees ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS employee_code text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS display_name text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS unit_number text;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS timezone text DEFAULT 'America/New_York';
ALTER TABLE employees ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS metadata jsonb DEFAULT '{}'::jsonb;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

UPDATE employees SET timezone = COALESCE(timezone, 'America/New_York') WHERE timezone IS NULL;
UPDATE employees SET active = COALESCE(active, true) WHERE active IS NULL;
UPDATE employees SET metadata = COALESCE(metadata, '{}'::jsonb) WHERE metadata IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_employees_code ON employees(employee_code);
CREATE INDEX IF NOT EXISTS idx_employees_role_active ON employees(role, active);
CREATE INDEX IF NOT EXISTS idx_employees_user_id ON employees(user_id);

CREATE TABLE IF NOT EXISTS employee_shifts (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
 employee_id uuid NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
 assignment_role text NOT NULL,
 weekday_iso smallint NOT NULL,
 start_time time NOT NULL,
 end_time time NOT NULL,
 effective_start_date date NOT NULL DEFAULT CURRENT_DATE,
 effective_end_date date,
 active boolean NOT NULL DEFAULT true,
 notes text,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_employee_shifts_weekday_iso CHECK (weekday_iso BETWEEN 1 AND 7)
);

ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS employee_id uuid;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS assignment_role text;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS weekday_iso smallint;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS start_time time;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS end_time time;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS effective_start_date date DEFAULT CURRENT_DATE;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS effective_end_date date;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE employee_shifts ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE UNIQUE INDEX IF NOT EXISTS ux_employee_shifts_unique_slot
 ON employee_shifts(employee_id, assignment_role, weekday_iso, start_time, end_time, effective_start_date);
CREATE INDEX IF NOT EXISTS idx_employee_shifts_lookup
 ON employee_shifts(employee_id, active, weekday_iso, start_time);

CREATE TABLE IF NOT EXISTS trip_work_assignments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 booking_reference text NOT NULL REFERENCES bookings(reference) ON DELETE CASCADE,
 driver_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
 dispatcher_employee_id uuid REFERENCES employees(id) ON DELETE SET NULL,
 assignment_status text NOT NULL DEFAULT 'ASSIGNED',
 assigned_at timestamptz NOT NULL DEFAULT now(),
 accepted_at timestamptz,
 completed_at timestamptz,
 note text,
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS booking_reference text;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS driver_employee_id uuid;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS dispatcher_employee_id uuid;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS assignment_status text DEFAULT 'ASSIGNED';
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS assigned_at timestamptz DEFAULT now();
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS accepted_at timestamptz;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS completed_at timestamptz;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS created_at timestamptz DEFAULT now();
ALTER TABLE trip_work_assignments ADD COLUMN IF NOT EXISTS updated_at timestamptz DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_trip_work_assignments_booking ON trip_work_assignments(booking_reference, assigned_at DESC);
CREATE INDEX IF NOT EXISTS idx_trip_work_assignments_driver ON trip_work_assignments(driver_employee_id, assignment_status);
CREATE INDEX IF NOT EXISTS idx_trip_work_assignments_dispatcher ON trip_work_assignments(dispatcher_employee_id, assignment_status);

INSERT INTO employees(employee_code, role, display_name, email, active, metadata)
VALUES
 ('DISP001', 'DISPATCHER', 'Dispatcher One', 'dispatcher1@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('DISP002', 'DISPATCHER', 'Dispatcher Two', 'dispatcher2@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD001', 'DRIVER', 'Marcus Bennett', 'driver01@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD002', 'DRIVER', 'Ethan Rodriguez', 'driver02@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD003', 'DRIVER', 'Noah Carter', 'driver03@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD004', 'DRIVER', 'Adrian Wallace', 'driver04@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD005', 'DRIVER', 'Julian Brooks', 'driver05@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD006', 'DRIVER', 'Caleb Morgan', 'driver06@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD007', 'DRIVER', 'Isaac Perry', 'driver07@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD008', 'DRIVER', 'Miles Cooper', 'driver08@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD009', 'DRIVER', 'Liam Foster', 'driver09@nexusmt.com', true, jsonb_build_object('source','migration_048')),
 ('NEXD010', 'DRIVER', 'Owen Simmons', 'driver10@nexusmt.com', true, jsonb_build_object('source','migration_048'))
ON CONFLICT (employee_code) DO UPDATE SET
 role = EXCLUDED.role,
 display_name = EXCLUDED.display_name,
 email = EXCLUDED.email,
 active = true,
 updated_at = now();

UPDATE employees e
SET user_id = u.id,
 updated_at = now()
FROM users u
WHERE lower(u.email) = lower(e.email)
 AND (e.user_id IS DISTINCT FROM u.id);

WITH weekdays AS (
 SELECT unnest(ARRAY[1,2,3,4,5]) AS weekday_iso
), dispatcher_shifts AS (
 SELECT e.id AS employee_id, 'DISPATCHER'::text AS assignment_role, w.weekday_iso, '07:00'::time AS start_time, '16:00'::time AS end_time
 FROM employees e
 CROSS JOIN weekdays w
 WHERE e.employee_code = 'DISP001'
 UNION ALL
 SELECT e.id AS employee_id, 'DISPATCHER'::text AS assignment_role, w.weekday_iso, '10:00'::time AS start_time, '19:00'::time AS end_time
 FROM employees e
 CROSS JOIN weekdays w
 WHERE e.employee_code = 'DISP002'
)
INSERT INTO employee_shifts(employee_id, assignment_role, weekday_iso, start_time, end_time, effective_start_date, active, notes)
SELECT ds.employee_id, ds.assignment_role, ds.weekday_iso, ds.start_time, ds.end_time, CURRENT_DATE, true,
 'Seeded dispatcher schedule'
FROM dispatcher_shifts ds
ON CONFLICT (employee_id, assignment_role, weekday_iso, start_time, end_time, effective_start_date)
DO UPDATE SET active = true, updated_at = now();

INSERT INTO schema_migrations(version,description)
VALUES('048.001','Workforce tables: employees, employee_shifts, trip_work_assignments plus dispatcher schedule seed')
ON CONFLICT(version) DO NOTHING;
