ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS seat_capacity integer;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS wheelchair_capacity integer;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS maintenance_interval_days integer DEFAULT 30;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS last_maintenance_date date;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS next_maintenance_date date;
ALTER TABLE vehicles ADD COLUMN IF NOT EXISTS maintenance_notes text;

UPDATE vehicles SET seat_capacity = COALESCE(seat_capacity, CASE
  WHEN vehicle_type = 'BUS_12_SEATER' THEN 12
  WHEN vehicle_type = 'VAN_4_SEAT_WHEELCHAIR' THEN 4
  WHEN vehicle_type LIKE 'AMBULANCE_%' THEN 2
  ELSE 4
END)
WHERE seat_capacity IS NULL;

UPDATE vehicles SET wheelchair_capacity = COALESCE(wheelchair_capacity, CASE
  WHEN vehicle_type = 'VAN_4_SEAT_WHEELCHAIR' THEN 1
  WHEN vehicle_type = 'BUS_12_SEATER' THEN 1
  ELSE 0
END)
WHERE wheelchair_capacity IS NULL;

UPDATE vehicles SET maintenance_interval_days = COALESCE(maintenance_interval_days, 30)
WHERE maintenance_interval_days IS NULL OR maintenance_interval_days < 7;

UPDATE vehicles
SET next_maintenance_date = COALESCE(
  next_maintenance_date,
  CASE
    WHEN last_maintenance_date IS NOT NULL THEN (last_maintenance_date + make_interval(days => maintenance_interval_days))::date
    ELSE (CURRENT_DATE + make_interval(days => maintenance_interval_days))::date
  END
)
WHERE next_maintenance_date IS NULL;

CREATE TABLE IF NOT EXISTS vehicle_maintenance_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  unit_number text NOT NULL,
  event_type text NOT NULL DEFAULT 'SERVICE',
  performed_on date NOT NULL,
  odometer integer,
  notes text,
  performed_by text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_vehicle_maintenance_events_unit_date
  ON vehicle_maintenance_events(unit_number, performed_on DESC);

INSERT INTO schema_migrations(version,description)
VALUES('049.001','Fleet maintenance schedule columns and maintenance events table')
ON CONFLICT(version) DO NOTHING;
